### PR TITLE
Fix startup for HA 2023.5 

### LINKED ISSUE #4: Errors on restart after upgrade to v1.0.12
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/iammeter_http/__init__.py:52
Integration: Iammeter_http
First occurred: 15:28:47 (1 occurrences)
Last logged: 15:28:47

Error setting up entry iammeter for iammeter_http
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/iammeter_http/__init__.py", line 22, in async_setup_entry
    coordinator = IammeterData(hass, entry)
  File "/config/custom_components/iammeter_http/__init__.py", line 52, in __init__
    self.port = entry.data[CONF_PORT]
KeyError: 'port'

**Error occurs on restart after upgrading from v1.0.9 to v1.0.12**
I have restored back to v1.0.9 til this issue can be resolved

Running HA:
Home Assistant 2023.3.5
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

Iammeter Information:

Firmware Ver.: ATVi.75.98.1@MX1290
Running Cloud Mode
Model: WEM3080T

### LINKED ISSUE #5: Failed to set up - HA  2023.5.0b3
hi guys, having issues with the integration starting in 2023.5.0b3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230428.0 - latest

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/iammeter_http/__init__.py", line 25, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### PR DESCRIPTION
**Pull request by grahambrown11**
change deprecated method
fixes #5 #6

### CODE REVIEW

**Comment by grahambrown11** [comment]
@miwyf or @lewei50 are you able to accept this an release this - many thanks
